### ISSUE TITLE
Some way of retrieving a LepTess' image dimensions?

### ISSUE THREAD

**Issue by kangalioo** [houqp/leptess#16]
Would it be possible to add a way to retrieve the dimensions of the image which is currently loaded in a LepTess instance?

**Comment by houqp** [comment]
We could add a helper method that uses `GetInputImage` API (https://github.com/tesseract-ocr/tesseract/blob/master/include/tesseract/baseapi.h#L139) to get a Pix object, then use it to return the dimension.

**Comment by kangalioo** [comment]
I had a go at implementing this. The Tesseract C++ library documentation was very hard to understand for me though, and I don't know if the code I wrote is sound.

Maybe you can be a better judge?

**Comment by kangalioo** [comment]
Oh damn, I misclicked on mobile 😅

**Comment by houqp** [comment]
@kangalioo that looks good to me, feel free to send a PR.
