### ISSUE TITLE
Fix all the places that Clippy lints

### ISSUE THREAD

**Issue by kangalioo** [houqp/leptess#21]
Looking at the code in VSCode, there's many lines of code that are linted by Clippy. It would be cool if all those cases were resolved

**Comment by kangalioo** [comment]
Oh I didn't see that since I looked at the code, a commit was already made to resolve the linted places.

This makes this issue.. completely obsolete. Sorry about that

**Comment by ccouzens** [comment]
No worries. I think I fixed them after noticing the same problem when writing the code for https://github.com/houqp/leptess/issues/12

Thanks for taking a positive interest in leptess 🙂
