### ISSUE TITLE
hocr output 

### ISSUE THREAD

**Issue by LennyPenny** [houqp/leptess#27]
Is there any way of getting hocr output instead of just the plain text output?

**Comment by ccouzens** [comment]
Not at the moment.

It doesn't look too difficult to add. I'll try and do so

**Comment by ccouzens** [comment]
@LennyPenny I've created a pull request. I can't add you as a reviewer, but I would still appreciate it if you could take a look.

https://github.com/houqp/leptess/pull/28

**Comment by ccouzens** [comment]
The crate has been released as 0.10.0 https://crates.io/crates/leptess/0.10.0
