### ISSUE TITLE
[REQ] setvariable eng.user-words

### ISSUE THREAD

**Issue by DartMen** [houqp/leptess#31]
A way to feed a list of words to supplement Tesseract would be very nice.

In a .NET implementation this seems possible by setting:
Tess.setVariable("user_words_suffix", "user-words");

Also consider adding a test method to verify user supplied words are loaded and actually used by Tesseract.

**Comment by ccouzens** [comment]
It sounds like we should be adding a way to call [set variable](https://tesseract-ocr.github.io/tessapi/5.x/a02438.html#a2e09259c558c6d8e0f7e523cbaf5adf5).

From there, you could use `"user_words_suffix", "user-words"` or any of the [other variables](https://ironsoftware.com/csharp/ocr/docs/questions/csharp-tesseract-config-configuration-variables/)

**Comment by ccouzens** [comment]
I thought I had commented on this yesterday. I'll re-comment as best as I remember.

---

To start, I'm going to try and generate methods for every single possible variable.

The list of variables can be found by running `tesseract --print-parameters`. Each variable is separated by a new line. Within a line, it's name tab example tab comment.

This will allow each variable to have a doc-comment generated for it. It will also allow us to forbid calling `setVariable` with an invalid variable name- in my observations each time an invalid variable name is used Tesseract leaks a small number of bytes of memory.

Unfortunately I cannot see how to determine which variables are numbers and which are strings.

If this proves too difficult, I'll fall back to just exposing `set_variable` and be done with it.

**Comment by houqp** [comment]
Instead of generating methods, how about generating an enum? Then we can have a safe `set_variable` wrapper method that takes the enum as param argument and value as string just like what `set_variable` does. This avoids the need to detect value type.

**Comment by ccouzens** [comment]
0.13.0 has support for set_variable
https://crates.io/crates/leptess/0.13.0

**Comment by yosefahab** [comment]
> 0.13.0 has support for set_variable
> https://crates.io/crates/leptess/0.13.0

is this through `TessApi::raw::set_variable()` ? which requires the use of a CStr ?

**Comment by ccouzens** [comment]
> > 0.13.0 has support for set_variable
> > https://crates.io/crates/leptess/0.13.0
> 
> is this through `TessApi::raw::set_variable()` ? which requires the use of a CStr ?

Hi, no.

Try `LepTess::set_variable`
https://houqp.github.io/leptess/leptess/struct.LepTess.html#method.set_variable

That takes an enum https://houqp.github.io/leptess/leptess/enum.Variable.html

**Comment by yosefahab** [comment]
> > > 0.13.0 has support for set_variable
> > > https://crates.io/crates/leptess/0.13.0
> > 
> > 
> > is this through `TessApi::raw::set_variable()` ? which requires the use of a CStr ?
> 
> Hi, no.
> 
> Try `LepTess::set_variable` https://houqp.github.io/leptess/leptess/struct.LepTess.html#method.set_variable
> 
> That takes an enum https://houqp.github.io/leptess/leptess/enum.Variable.html

oh i see, i had used the LepTess struct before, but i felt a bit limited so i started using the low level api module.
There were a couple of problems:
1. not being able to use `Pix`
2. getting `Empty page!!` error when converting a `DynamicImage` variable into a byte array which is required by `set_image_from_mem()`
