### ISSUE TITLE
CI keeps failing

### ISSUE THREAD

**Issue by ccouzens** [houqp/leptess#37]
The tests keep timing out on circle ci, which is reported as a failure.

EG: https://app.circleci.com/pipelines/github/houqp/leptess/144/workflows/840b32fe-bb25-49f0-81df-23de6f77514b/jobs/174

On my laptop, they take about 7 seconds to run through (not including compiling) which is a reasonable time.

I [tried to decrease the concurrency](https://github.com/houqp/leptess/commit/59ada5fdb3df3de78037259defec607f6db6bca1), to see if that helped. It didn't.

**Comment by ccouzens** [comment]
Ideas on how to tackle this:

1. Switch to github actions
2. configure some tests not to run on CI

**Comment by houqp** [comment]
Yeah, let's switch to Github action!
