### ISSUE TITLE
failed to run custom build command for `tesseract-sys v0.5.7`

### ISSUE THREAD

**Issue by bart-krakowski** [houqp/leptess#40]
When I'm trying to add this package to the `Cargo.toml` file I'm getting the following error:
`failed to run custom build command for `tesseract-sys v0.5.7`

OS: MacOS 12

**Comment by ccouzens** [comment]
Hello,

I think you might be having this issue https://github.com/ccouzens/tesseract-sys/issues/4

The version of `clang` that Apple ships has an incompatibility with `bindgen`.

Can you see if these steps help?

https://github.com/ccouzens/tesseract-sys/issues/4#issuecomment-748373340

**Comment by ccouzens** [comment]
Closing, as I've changed how tesseract-sys builds on Mac to be simpler.

https://github.com/ccouzens/tesseract-sys/pull/17
