### ISSUE TITLE
Show tesseract and leptonica version function?

### ISSUE THREAD

**Issue by kvnxiao** [houqp/leptess#46]
Does there currently exist a function that can fetch and show the currently used version of tesseract and leptonica? If not, this would be a great addition. I am using leptess in a GUI application and would like to be able to show this information in the "About" option popup.

It would be great if they could be included here as a wrapper to unsafe C_str conversion calls so that I don't have to explicitly declare dependencies on `tesseract-sys` + `leptonica-sys` and do:
```rust
unsafe {
    let tesseract_ver = CStr::from_ptr(tesseract_sys::TessVersion());
    let leptonica_ver = CStr::from_ptr(leptonica_sys::getLeptonicaVersion());
    let leptonica_libs_ver = CStr::from_ptr(leptonica_sys::getImagelibVersions());
	// ...
}
```

**Comment by houqp** [comment]
I don't think so, PRs welcome :)

**Comment by ccouzens** [comment]
leptonica-plumbing 0.6.0 and tesseract-plumbing 0.7.1 have both been published to support this

**Comment by kvnxiao** [comment]
Thanks! Will the Cargo.toml file here need to be updated to set `tesseract-plumbing` dependency version as `~0.7`?

**Comment by ccouzens** [comment]
> Thanks! Will the Cargo.toml file here need to be updated to set `tesseract-plumbing` dependency version as `~0.7`?

It depends.

If you want to use the methods directly from tesseract-plumbing then you can add the dependency to your app.

If you want to add the methods to leptess, you will need to update leptess's dependencies (and add version methods).

**Comment by kvnxiao** [comment]
Thanks, I think we can leave it as is like this as part of the *-plumbing repositories.
