### ISSUE TITLE
Documentation on docs.rs is broken

### ISSUE THREAD

**Issue by timvisee** [houqp/leptess#5]
Since the `0.7.0` release, it seems that the documentation on `docs.rs` is broken.  
See: https://docs.rs/leptess/0.7.0

It looks like this is because of the changed method for creating library bindings. It doesn't meet all requirements in the environment the docs are built in.  
See the log at: https://docs.rs/crate/leptess/0.7.0/builds

I'm afraid this requires a self-hosted version of this documentation (could be hosted through GitHub pages). Would it be a good idea to do this?

**Comment by houqp** [comment]
Yeah, good catch. Are you interested in helping make this change?

We can use circleci to build the docs and publish to gh pages.
