### ISSUE TITLE
Suppressing std output logs

### ISSUE THREAD

**Issue by yosefahab** [houqp/leptess#50]
Is there a way to suppress logs like (Estimating resolution as X) from being printed to the std output? its really slowing down the performance.

**Comment by houqp** [comment]
I am pretty sure there is a way to configure the logging verbosity in the C API, we just need to find it and expose it through the Rust interface.

**Comment by f2calv** [comment]
@yosefahab you can get rid of the warning by calling `set_source_resolution` explicitly *after* `set_image` ([more info](https://github.com/ccouzens/tesseract-plumbing/blob/main/src/tess_base_api.rs#L227)), i.e.

```rust
let mut lt = leptess::LepTess::new(None, "eng").unwrap();
lt.set_image(img_uri).unwrap();
//in my case my source JPGs are 96 dpi
lt.set_source_resolution(96);
```
