### ISSUE TITLE
sharing TessApi between threads

### ISSUE THREAD

**Issue by yosefahab** [houqp/leptess#51]
Is there a way to share TessApi instances between threads safely? i believe recreating an instance each time would be expensive, especially when applying OCR on thousands of images. perhaps using locks or atomics.

**Comment by houqp** [comment]
I think the best thing to do here is to create one instance per thread, then you can spread the load between all the threads.

**Comment by yosefahab** [comment]
I was able to wrap a Leptess instance in an Arc and a Mutex as follows:
`let leptess = Arc::new(Mutex::new(LepTess::new(None, "eng").unwrap()));`
It is significantly slower, i think due to the lock mechanism. But it works nontheless, since the lock is released after the ocr is complete, there shouldn't be any issue with the object modification.

**Comment by houqp** [comment]
@yosefahab adding that lock and share it with multiple thread will not speed things up I believe because you are still only running only one OCR scan at a time sequentially but just at different CPU cores and with extra mutex overhead. If you want maximum performance, the best thing to do is to run one in each thread without mutex.

**Comment by yosefahab** [comment]
> @yosefahab adding that lock and share it with multiple thread will not speed things up I believe because you are still only running only one OCR scan at a time sequentially but just at different CPU cores and with extra mutex overhead. If you want maximum performance, the best thing to do is to run one in each thread without mutex.

That is true to an extent, I tried having a pool of ready created instances of size num_threads, and it gave a slightly better performance than having to create an instance on every function call.
