### ISSUE TITLE
Supported image types

### ISSUE THREAD

**Issue by yosefahab** [houqp/leptess#52]
Is the [image](https://crates.io/crates/image) crate (or others) supported ? i need to apply intensive image processing tasks before passing them to leptess and i'm not sure if Pix is flexible enough.

**Comment by ccouzens** [comment]
Hi, yes indirectly

See this example

https://github.com/houqp/leptess/blob/master/examples/set_from_image_crate.rs

Probably we should make it easier by having an optional feature that provides a more direct method.
